### ISSUE TITLE
Offsets for arm64 (A11 and earlier) and 15.x

### ISSUE THREAD

**Issue by TheMasterOfMike** [BenjaminHornbeck6/KFD-Offsets#3]
I get this is - by no means - a priority for you, but how practical would it be to do the same things that you did to get these offsets for arm64 devices as well, and then also for iOS 15 (since we know kfd does work there - would also be nice if it worked on 14.x but nobody has tested kfd there last I checked)

**Comment by BenjaminHornbeck6** [comment]
Libpatchfinder doesn’t support it.
